Repository money-poly/kwangsang, pull requests merged in 2024-07, with the labels that each got.

#48 Fix: "스크롤 동기화 문제 수정"
  lib/screens/home/best_product/best_product_view.dart
  lib/screens/home/limit_stock/limit_stock_view.dart
  lib/screens/home/new_product/new_product_view.dart
  lib/screens/home/new_product/widgets/sale_store_card.dart
  lib/screens/home/recommend/recommend_view.dart
Labels: bug, P1

#49 Refector: "NumberFormat 리펙토링"
  lib/screens/home/recommend/recommend_view.dart
  lib/screens/home/widgets/item_card.dart
  lib/screens/home/widgets/item_discount_widget.dart
  lib/screens/menu/menu_bottom_sheet.dart
  lib/screens/menu/menu_view.dart
  lib/screens/menu/widgets/menu_bottom_sheet_card.dart
  lib/screens/purchase/purchase_check_view.dart
  lib/screens/purchase/widgets/soldout_menu_card.dart
  lib/screens/purchase_info/widgets/purchase_info_detail.dart
  lib/utils/extensions.dart
  lib/utils/number_formatter.dart
  lib/widgets/countable_menu_card.dart
  lib/widgets/menu_card.dart
  lib/widgets/store_card.dart
Labels: P2, refactor

#50 Fix: "MediaQuery padding zero 해결"
  lib/screens/menu/menu_bottom_sheet.dart
  lib/screens/menu/menu_more_view.dart
  lib/screens/menu/menu_view.dart
Labels: bug, P1

#52 Fix: "화면 pop 시 지도 잔상 늦게 사라짐"
  android/app/build.gradle
  android/build.gradle
  devtools_options.yaml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/providers/custom_router.dart
  lib/providers/position_provider.dart
  lib/screens/home/home_view.dart
  lib/screens/map/map_main_view_model.dart
  lib/screens/map/map_store_view.dart
  lib/screens/map/map_store_view_model.dart
  lib/screens/map/widgets/map_store_card.dart
  lib/screens/map/widgets/store_info_row.dart
  lib/screens/menu/menu_bottom_sheet.dart
  lib/screens/menu/menu_more_view.dart
  lib/screens/menu/menu_view.dart
  lib/screens/menu/menu_view_model.dart
  lib/screens/purchase_info/widgets/purchase_info_map.dart
  lib/screens/search/widgets/search_after_tab.dart
  lib/utils/extensions.dart
  lib/widgets/countable_menu_card.dart
  lib/widgets/menu_card.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, P2

#54 Fix: "go_router path 상수화 및 버그수정"
  lib/constants/routes.dart
  lib/providers/custom_router.dart
  lib/screens/home/home_view.dart
  lib/screens/login/login_view.dart
  lib/screens/map/map_main_view.dart
  lib/screens/map/map_store_view.dart
  lib/screens/menu/menu_bottom_sheet.dart
  lib/screens/menu/menu_view.dart
  lib/screens/navigation/onboarding.dart
  lib/screens/order/order_ing_view.dart
  lib/screens/search/widgets/search_after_tab.dart
Labels: bug, P0, refactor

#59 Feat: "정렬 옵션 바텀시트 구현"
  lib/enums/menu_sort_option.dart
  lib/screens/home/best_product/best_product_view.dart
  lib/widgets/sort_bottom_sheet.dart
Labels: feature, P1

#61 Refector: "enum 리펙토링"
  lib/enums/category.dart
  lib/enums/menu_status.dart
  lib/enums/purchase_info_phase.dart
  lib/models/menu/menu_model.dart
  lib/models/menu/menu_model.freezed.dart
  lib/models/menu/menu_model.g.dart
  lib/screens/home/best_product/best_product_view.dart
  lib/screens/home/home_view_model.dart
  lib/screens/home/limit_stock/limit_stock_view.dart
  lib/screens/purchase_info/purchase_info_view.dart
  lib/screens/purchase_info/purchase_info_view_model.dart
  lib/screens/purchase_info/widgets/purchase_info_map.dart
  lib/screens/purchase_info/widgets/purchase_info_progress_widget.dart
  lib/utils/menu_status_util.dart
  lib/widgets/menu_card.dart
  lib/widgets/menu_status_widget.dart
Labels: P1, refactor

#57 Feat: "카테고리 상세 화면 및 프랜차이즈 화면"
  lib/constants/routes.dart
  lib/providers/custom_router.dart
  lib/screens/home/category_view.dart
  lib/screens/home/category_view_model.dart
  lib/screens/home/franchise_view.dart
  lib/screens/home/recommend/recommend_view.dart
  lib/screens/home/widgets/count_and_sort_title.dart
  lib/screens/home/widgets/franchise_card.dart
  lib/screens/login/non_member_view.dart
Labels: feature, P0

#56 Refactor: "fromJson 통일"
  lib/models/menu/menu_detail_model.dart
  lib/models/menu/menu_model.dart
  lib/models/menu/menu_model.freezed.dart
  lib/models/menu/menu_model.g.dart
  lib/models/store/store_detail_model.dart
  lib/models/store/store_home_model.dart
  lib/models/store/store_home_model.freezed.dart
  lib/models/store/store_home_model.g.dart
  lib/models/store/store_model.dart
  lib/models/store/store_model.freezed.dart
  lib/models/store/store_model.g.dart
  lib/screens/map/widgets/map_store_card.dart
  lib/services/map_service.dart
  lib/utils/menu_status_util.dart
Labels: P0, refactor

#63 Feat: "홈-랭킹 탭 뷰 모델 구현"
  lib/enums/category.dart
  lib/enums/loading_status.dart
  lib/enums/menu_sort_option.dart
  lib/models/menu/menu_listitem_model.dart
  lib/models/menu/menu_listitem_model.freezed.dart
  lib/models/menu/menu_listitem_model.g.dart
  lib/models/menu/menu_model.dart
  lib/models/store/store_model.dart
  lib/models/store/store_model.freezed.dart
  lib/models/store/store_model.g.dart
  lib/providers/custom_router.dart
  lib/screens/home/best_product/best_product_view.dart
  lib/screens/home/best_product/best_product_view_model.dart
  lib/services/home_service.dart
  lib/utils/extensions.dart
  lib/widgets/menu_rank_card.dart
  lib/widgets/sort_bottom_sheet.dart
Labels: feature, P1
